services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
    plan: free
    build:
      - apt-get update && apt-get install -y cmake
